site_name: Gluu Server
site_description: An SSO, Federation and API Access Management suite
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources
repo_url: https://github.com/GluuFederation/docs
theme: spacelab 

pages:

# Home Page
- ['./index.md', 'Home']

# Admin Guide Sections
- ['admin-guide/introduction/index.md', 'Admin Guide', 'introduction']
- ['admin-guide/installation/index.md', 'Admin Guide', 'Installation']
- ['admin-guide/configuration/index.md', 'Admin Guide', 'Configuration']
- ['admin-guide/custom-look/index.md', 'Admin Guide', 'Customizing Look and Feel']
- ['admin-guide/certificates/index.md', 'Admin Guide', 'Certificates']
- ['admin-guide/user-management/index.md', 'Admin Guide', 'User Management']
- ['admin-guide/authentication/index.md', 'Admin Guide', 'Authentication']
- ['admin-guide/saml/index.md', 'Admin Guide', 'SAML']
- ['admin-guide/openid-connect/index.md', 'Admin Guide', 'OpenID Connect']
- ['admin-guide/uma/index.md', 'Admin Guide', 'UMA']
- ['admin-guide/interception-scripts/index.md', 'Admin Guide', 'Interception Scripts']
- ['admin-guide/multiparty-federation/index.md', 'Admin Guide', 'MultiParty Federation']
- ['admin-guide/oxPush/index.md', 'Admin Guide', 'oxPush']

# Reference sections
- ['reference/configuration/index.md', 'Reference', 'Configuration']
- ['reference/oxTrust/index.md', 'Reference', 'oxTrust User Interface']
- ['reference/ldap/index.md', 'Reference', 'LDAP Schema']
- ['reference/lib/index.md', 'Reference', 'Libraries']
- ['reference/api/index.md', 'Reference', 'APIs']

# Articles
- ['articles/apache-saml.md', 'Articles', 'Apache SAML']
- ['articles/java-saml.md', 'Articles', 'Java SAML']
- ['articles/apache-oauth2.md', 'Articles', 'Apache OpenID Connect / UMA']
- ['articles/nginx-oauth2.md', 'Articles', 'nginx OpenID Connect / UMA']
- ['articles/js-connect.md', 'Articles', 'JavaScript OpenID Connect RP']
- ['articles/java-connect.md', 'Articles', 'Java OpenID Connect RP']
- ['articles/scim-client.md', 'Articles', 'Java SCIM client']
- ['articles/mobile-api.md', 'Articles', 'Mobile - Headless API : Connect / UMA']

# Sub Pages of introduction 
- ['admin-guide/introduction/architecture.md', '**HIDDEN**']
- ['admin-guide/introduction/design-goals.md', '**HIDDEN**']
- ['admin-guide/introduction/gluu-server-mission.md', '**HIDDEN**']
- ['admin-guide/introduction/history.md', '**HIDDEN**']
- ['admin-guide/introduction/licenses.md', '**HIDDEN**']

# Sub Pages of Admin Guide / installation
- ['admin-guide/installation/redhat.md', '**HIDDEN**']
- ['admin-guide/installation/ubuntu.md', '**HIDDEN**']
- ['admin-guide/installation/centos.md', '**HIDDEN**']
- ['admin-guide/installation/debian.md', '**HIDDEN**']
- ['admin-guide/installation/windows.md', '**HIDDEN**']
- ['admin-guide/installation/mac.md', '**HIDDEN**']
- ['admin-guide/installation/juju.md', '**HIDDEN**']
- ['admin-guide/installation/build.md', '**HIDDEN**']

# Sub Pages of Admin Guide / Configuration
- ['admin-guide/configuration/asimba.md', '**HIDDEN**']
- ['admin-guide/configuration/oxAuth.md', '**HIDDEN**']
- ['admin-guide/configuration/oxPush.md', '**HIDDEN**']
- ['admin-guide/configuration/oxTrust.md', '**HIDDEN**']
- ['admin-guide/configuration/shibIDP.md', '**HIDDEN**']
- ['admin-guide/configuration/oxProx.md', '**HIDDEN**']

# Sub Pages of Customizing Look and Feel
- ['admin-guide/custom-look/authentication.md', '**HIDDEN**']
- ['admin-guide/custom-look/defaults.md', '**HIDDEN**']
- ['admin-guide/custom-look/registration.md', '**HIDDEN**']
- ['admin-guide/custom-look/saml-discovery.md', '**HIDDEN**']
- ['admin-guide/custom-look/user-profile.md', '**HIDDEN**']
- ['admin-guide/custom-look/xhtml.md', '**HIDDEN**']

# Sub Pages of Admin Guide / Certificates 
- ['admin-guide/certificates/https.md', '**HIDDEN**']
- ['admin-guide/certificates/saml.md', '**HIDDEN**']
- ['admin-guide/certificates/openid.md', '**HIDDEN**']
- ['admin-guide/certificates/federation.md', '**HIDDEN**']
- ['admin-guide/certificates/ldap.md', '**HIDDEN**']

# Sub pages of Admin Guide / User-Management
- ['admin-guide/user-management/scim.md', '**HIDDEN**']
- ['admin-guide/user-management/ldap-sync.md', '**HIDDEN**']
- ['admin-guide/user-management/local-admin.md', '**HIDDEN**']
- ['admin-guide/user-management/registration.md', '**HIDDEN**']
- ['admin-guide/user-management/self-service.md', '**HIDDEN**']
- ['admin-guide/user-management/invitation-code-registration.md', '**HIDDEN**']

# Sub pages of Admin Guide / Authentication
- ['admin-guide/authentication/ldap.md', '**HIDDEN**']
- ['admin-guide/authentication/custom.md', '**HIDDEN**']
- ['admin-guide/authentication/oxPush.md', '**HIDDEN**']
- ['admin-guide/authentication/saml.md', '**HIDDEN**']
- ['admin-guide/authentication/cas.md', '**HIDDEN**']
- ['admin-guide/authentication/google.md', '**HIDDEN**']
- ['admin-guide/authentication/duo.md', '**HIDDEN**']
- ['admin-guide/authentication/toopher.md', '**HIDDEN**']

# Sub pages of Admin Guide / SAML
- ['admin-guide/saml/outbound-saml.md', '**HIDDEN**']
- ['admin-guide/saml/inbound-saml.md', '**HIDDEN**']
- ['admin-guide/saml/saml-registration.md', '**HIDDEN**']
- ['admin-guide/saml/saml-sp-configuration.md', '**HIDDEN**']

# Sub Pages of Admin Guide / OpenID Connect
- ['admin-guide/openid-connect/registration.md', '**HIDDEN**']
- ['admin-guide/openid-connect/discovery.md', '**HIDDEN**']
- ['admin-guide/openid-connect/scopes.md', '**HIDDEN**']
- ['admin-guide/openid-connect/client-config.md', '**HIDDEN**']

# Sub pages of Admin Guide / UMA 
- ['admin-guide/uma/discovery.md', '**HIDDEN**']
- ['admin-guide/uma/resource-registration.md', '**HIDDEN**']
- ['admin-guide/uma/policy.md', '**HIDDEN**']
- ['admin-guide/uma/uma-scopes.md', '**HIDDEN**']
- ['admin-guide/uma/mod_ox.md', '**HIDDEN**']

# Sub pages of Admin Guide / Interception Scripts 
- ['admin-guide/interception-scripts/authentication.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/authorization.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/id-generation.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/attribute-transformation.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/post-registration.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/pre-registration.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/logout.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/saml-discovery.md', '**HIDDEN**']

# Sub pages of Admin Guide / oxPush
- ['admin-guide/oxPush/cordova-app.md', '**HIDDEN**']
- ['admin-guide/oxPush/oxPush-server.md', '**HIDDEN**']
- ['admin-guide/oxPush/oxPush-crypto.md', '**HIDDEN**']

# Sub pages of Multiparty Federation 
- ['admin-guide/multiparty-federation/saml-federation.md', '**HIDDEN**']
- ['admin-guide/multiparty-federation/oauth2-federation.md', '**HIDDEN**']
- ['admin-guide/multiparty-federation/federation-public-website.md', '**HIDDEN**']

- ['reference/lib/openid-connect.md', '**HIDDEN**']
- ['reference/lib/uma.md', '**HIDDEN**']
- ['reference/lib/scim.md', '**HIDDEN**']
- ['reference/lib/saml.md', '**HIDDEN**']
- ['reference/lib/user-management.md', '**HIDDEN**']

# Sub pages of Reference / LDAP
- ['reference/ldap/opendj-schema.md', '**HIDDEN**']
- ['reference/ldap/openldap-schema.md', '**HIDDEN**']
- ['reference/ldap/389ds-schema.md', '**HIDDEN**']
- ['reference/ldap/namespace.md', '**HIDDEN**']
- ['reference/ldap/indexing.md', '**HIDDEN**']
- ['reference/ldap/replication.md', '**HIDDEN**']

# Sub pages of Reference / Configuration
- ['reference/configuration/system.md', '**HIDDEN**']
- ['reference/configuration/oxAuth.md', '**HIDDEN**']
- ['reference/configuration/oxTrust.md', '**HIDDEN**']
- ['reference/configuration/shibIDP.md', '**HIDDEN**']
- ['reference/configuration/asimba.md', '**HIDDEN**']
- ['reference/configuration/opendj.md', '**HIDDEN**']
- ['reference/configuration/openldap.md', '**HIDDEN**']
- ['reference/configuration/jagger.md', '**HIDDEN**']
- ['reference/configuration/oxPush.md', '**HIDDEN**']
- ['reference/configuration/oxProx.md', '**HIDDEN**']
- ['reference/configuration/mysql.md', '**HIDDEN**']
- ['reference/configuration/memcached.md', '**HIDDEN**']

# Sub pages of Reference / Configuration
- ['reference/oxTrust/configuration.md', '**HIDDEN**']
- ['reference/oxTrust/oauth2.md', '**HIDDEN**']
- ['reference/oxTrust/personal.md', '**HIDDEN**']
- ['reference/oxTrust/saml.md', '**HIDDEN**']
- ['reference/oxTrust/users.md', '**HIDDEN**']
